module ErrorEnum
	USER_EXIST         	 = "error_0"
	EMAIL_MIBILE_BLANK 	 = "error_1"
	PASSWORD_BLANK 	   	 = "error_2"
	USER_NOT_EXIST 	   	 = "error_3"
	PASSWORD_ERROR 	   	 = "error_4"
	EMAIL_EXIST    	   	 = "error_5"
	MOBILE_EXIST   	   	 = "error_6"
	QQ_EXIST       	   	 = "error_7"
	WECHART_EXIST  	   	 = "error_8"
	SKYPE_EXIST    	   	 = "error_9"
	GTALK_EXIST    	   	 = "error_10"
	TWITTER_EXIST  	   	 = "error_11"
	FACEBOOK_EXIST 	   	 = "error_12"
	EMAIL_BLANK        	 = "error_13"
	MOBILE_BLANK       	 = "error_14"
	NAME_BLANK         	 = "error_15"
	ORDER_NOT_EXIST    	 = "error_16"
	ORDER_CAN_NOT_CANCEL = "error_17" 
	MOBILE_ERROR         = "error_18"
end 