:concurrency: 5
:verbose: false
:pidfile: tmp/pids/batch.pid
:logfile: log/batch.log
:queues:
    - mic_batch
development:
  :concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: 20
